### ISSUE TITLE
Mistake in documentation about the location of the object file

### ISSUE THREAD

**Issue by sectorsize512** [IBM/og#10]
Documentation says that "The default location is in the object sub-directory of the OG distribution." But it seems that object/ directory is created in the current working directory of the og process. E.g., if OG is executed like this:

# cd /tmp/test
# /home/vass/og/og test.json

the object/ directory is createsd in /tmp/test/

**Comment by nlahmedIBM** [comment]
Thanks. Corrected the user guide to  reflect that.
